pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JAVA_HOME'
    }
    
    parameters {
        string(name: 'Branch_Name', defaultValue: 'working_v1.0', description: 'Git Branch to be built')
    }
    
    environment {
        SONARQUBE_ENV = 'LocalSonar'
        SUREFIRE_REPORT_PATTERN = "target/surefire-reports/*"
        EXTENT_REPORT_PATTERN = "target/ExtentReport_*.html"
    }

    stages {
        
        
        stage('Archive Reports') {
            steps {
                archiveArtifacts artifacts: "${SUREFIRE_REPORT_PATTERN}, ${EXTENT_REPORT_PATTERN}", fingerprint: true
            }
        }

        stage('Parse Extent Report') {
            steps {
                script {
                    // Find the actual extent report file (resolve wildcard)
                    def extentFiles = findFiles(glob: "${EXTENT_REPORT_PATTERN}")
                    def extentFile = extentFiles ? extentFiles[0].path : null

                    def passedCount = "0"
                    def failedCount = "0"
                    def skippedCount = "0"

                    if (extentFile && fileExists(extentFile)) {
                        def content = readFile(extentFile)

                        def passMatch = content =~ /Tests Passed<\/.*?>(\d+)/
                        def failMatch = content =~ /Tests Failed<\/.*?>(\d+)/
                        def skipMatch = content =~ /Tests Skipped<\/.*?>(\d+)/

                        passedCount  = passMatch ? passMatch[0][1] : "0"
                        failedCount  = failMatch ? failMatch[0][1] : "0"
                        skippedCount = skipMatch ? skipMatch[0][1] : "0"
                    } else {
                        echo "Extent report not found!"
                    }
 				if(passedCount!="0") {
					 env.PASSED_COUNT = passedCount
  					 echo "Passed count found: ${passedCount}"
				} else {
  					 echo "No Passed count found: ${passedCount}"
  					 passedCount = 10
				}
                    env.PASSED_COUNT = passedCount
                    env.FAILED_COUNT = failedCount
                    env.SKIPPED_COUNT = skippedCount
                    env.EXTENT_REPORT_FILE = extentFile ?: ''
                }
            }
        }
        
        stage('Send Email') {
            steps {
                script {
                    def surefireReport = "target/surefire-reports/index.html"
                    def extentReportFile = env.EXTENT_REPORT_FILE

                    emailext(
                        subject: "Test Execution Report - ${currentBuild.fullDisplayName}",
                        body: """
                            <h3>Automation Test Summary</h3>
                            <table border="1" cellpadding="5">
                                <tr><th>Passed</th><th>Failed</th><th>Skipped</th></tr>
                                <tr>
                                    <td style="color:green">${env.PASSED_COUNT}</td>
                                    <td style="color:red">${env.FAILED_COUNT}</td>
                                    <td style="color:orange">${env.SKIPPED_COUNT}</td>
                                </tr>
                            </table>
                            <br>
                            <b>Extent Report:</b> <a href="${BUILD_URL}artifact/${extentReportFile}">View Report</a><br>
                            <b>Surefire Report:</b> <a href="${BUILD_URL}artifact/${surefireReport}">View Report</a>
                            <br><br>
                            <i>Generated by Jenkins on ${new Date()}</i>
                        """,
                        to: 'venki.ralami@gmail.com',
                        mimeType: "text/html",
                        attachmentsPattern: extentReportFile ?: ''
                    )
                }
            }
        }

        stage('Publish HTML Report') {
            steps {
                publishHTML([
                    reportDir: 'target/surefire-reports',
                    reportFiles: 'index.html',
                    reportName: 'Surefire Report',
                    keepAll: true,
                    allowMissing: false,
                    alwaysLinkToLastBuild: true
                ])
            }
        }
        
       
    }

    post {
        always {
            archiveArtifacts artifacts: "target/surefire-reports/index.html, ${env.EXTENT_REPORT_FILE}", fingerprint: true
        }
    }
}
